# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DojoSecretsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='secret_likes',
            new_name='related_likes',
        ),
        migrations.RenameField(
            model_name='secret',
            old_name='user',
            new_name='user_secrets',
        ),
    ]
