# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogAndRegApp', '0001_initial'),
        ('DojoSecretsApp', '0004_auto_20170328_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='LogAndRegApp.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='target',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='DojoSecretsApp.Secret'),
            preserve_default=False,
        ),
    ]
