# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogAndRegApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favquote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_fquote', to='LogAndRegApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('quoted_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_quote', to='LogAndRegApp.User')),
            ],
        ),
        migrations.AddField(
            model_name='fquotes',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fquotes', to='QuotesApp.Quotes'),
        ),
    ]
