# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogAndRegApp', '0001_initial'),
        ('CoursesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(related_name='all_user', to='LogAndRegApp.User'),
        ),
    ]
